FROM php:8.2-apache

# Установка расширений PHP
RUN docker-php-ext-install mysqli pdo pdo_mysql

# ОТКЛЮЧАЕМ ВСЕ MPM модули
RUN a2dismod mpm_event || true
RUN a2dismod mpm_worker || true

# ВКЛЮЧАЕМ только mpm_prefork
RUN a2enmod mpm_prefork

# Включаем другие модули
RUN a2enmod rewrite headers

# Копирование исходного кода
COPY src/ /var/www/html/

# Настройка прав
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

EXPOSE 80

CMD ["apache2-foreground"]
